<a href="https://colab.research.google.com/github/satyaveni-020408/Python-Assignment-1/blob/main/PYTHON_DA_ASSIGNMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# PYTHON DA ASSIGNMENT 1
# Data Analysis using NumPy and Pandas
# ============================================================

import numpy as np
import pandas as pd

print("=" * 60)
print("PYTHON DA ASSIGNMENT 1: NUMPY AND PANDAS")
print("=" * 60)


# ============================================================
# PART 1: NUMPY ARRAY OPERATIONS
# ============================================================

print("\n" + "=" * 60)
print("PART 1: NUMPY ARRAY OPERATIONS")
print("=" * 60)

# 1. Create a 1D NumPy Array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("\n1. Week 1 Temperature Array:")
print(temperatures_w1)

# 2. Inspection and Properties
print("\n2. Inspection and Properties:")
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

# 3. Array Operations
fahrenheit = (temperatures_w1 * 9/5) + 32

print("\n3. Temperature in Fahrenheit:")
print(fahrenheit)

print("\nMaximum Temperature:", temperatures_w1.max())
print("Minimum Temperature:", temperatures_w1.min())
print("Mean Temperature:", temperatures_w1.mean())

# 4. Array Slicing and Indexing
print("\n4. Array Slicing and Indexing:")

print("First three days:", temperatures_w1[:3])
print("Weekend (last two days):", temperatures_w1[-2:])
print("Middle three days:", temperatures_w1[2:5])


# ============================================================
# 5. CREATE A 2D ARRAY
# ============================================================

print("\n" + "=" * 60)
print("5. 2D NUMPY ARRAY")
print("=" * 60)

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("\nTemperatures for two weeks:")
print(temperatures)

# 6. Inspect and Slice the 2D Array
print("\n6. 2D Array Properties:")
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

print("\nWeek 1 temperatures:")
print(temperatures[0])

print("\nWeek 2 temperatures:")
print(temperatures[1])

print("\nWeek 1 weekend:")
print(temperatures[0, -2:])

print("\nWeek 2 weekend:")
print(temperatures[1, -2:])


# ============================================================
# PART 2: PANDAS SERIES
# ============================================================

print("\n" + "=" * 60)
print("PART 2: PANDAS SERIES")
print("=" * 60)

# 1. Creating Pandas Series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("\n1. Marks Series:")
print(marks)

# 2. Indexing and Slicing
print("\n2. Indexing and Slicing:")

# Integer index position - first rank student
print("\nMark of 1st rank student:")
print(marks.iloc[0])

# loc - top 3 ranks
print("\nMarks of Top 3 Rank Students:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# iloc - 3rd rank student
print("\nMark of 3rd rank student:")
print(marks.iloc[2])

# Boolean mask - marks greater than 90
print("\nStudents with marks greater than 90:")
print(marks[marks > 90])

# 3. Manipulating Series
print("\n3. Manipulating Series:")

# Modify 1st rank mark to 100
marks['Rank1'] = 100
print("\nAfter changing Rank1 mark to 100:")
print(marks)

# Remove last rank
marks = marks.drop('Rank5')
print("\nAfter removing Rank5:")
print(marks)

# Calculate CGPA
cgpa = marks / 10
print("\nCGPA (Marks divided by 10):")
print(cgpa)


# ============================================================
# PART 3: PANDAS DATAFRAME
# ============================================================

print("\n" + "=" * 60)
print("PART 3: PANDAS DATAFRAME")
print("=" * 60)

# 1. Creating Pandas DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Clothing', 'Furniture',
        'Electronics', 'Clothing'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print("\n1. Transactions DataFrame:")
print(transactions)


# ============================================================
# 2. DATA EXPLORATION
# ============================================================

print("\n" + "=" * 60)
print("2. DATA EXPLORATION")
print("=" * 60)

# Display head
print("\nFirst 5 rows (head):")
print(transactions.head())

# Display tail
print("\nLast 5 rows (tail):")
print(transactions.tail())

# Shape
print("\nShape:")
print(transactions.shape)

# Column names
print("\nColumn Names:")
print(transactions.columns)

# Data types
print("\nData Types:")
print(transactions.dtypes)

# Basic information
print("\nBasic Information:")
transactions.info()

# Display ProductCategory and Amount
print("\nProductCategory and Amount:")
print(transactions[['ProductCategory', 'Amount']])

# Retrieve last 3 columns using iloc
print("\nLast 3 Columns using iloc:")
print(transactions.iloc[:, -3:])

# Retrieve last 3 columns using loc
print("\nLast 3 Columns using loc:")
print(transactions.loc[:, ['ProductCategory', 'Region', 'Amount']])

# Filter Region = North and Amount > 200
print("\nTransactions where Region is North and Amount is greater than 200:")
print(transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
])

# Value counts for ProductCategory
print("\nValue Counts of ProductCategory:")
print(transactions['ProductCategory'].value_counts())

# Unique values in Region
print("\nUnique Values in Region:")
print(transactions['Region'].unique())


# Group by Region and find mean Amount
print("\nMean Amount for Each Region:")
print(transactions.groupby('Region')['Amount'].mean())


# ============================================================
# 3. MANIPULATING THE DATAFRAME
# ============================================================

print("\n" + "=" * 60)
print("3. MANIPULATING THE DATAFRAME")
print("=" * 60)

# Modify Amount for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print("\nAfter changing TransactionID 102 Amount to 165:")
print(transactions)

# Add Discount column - 10% of Amount
transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter adding Discount column (10% of Amount):")
print(transactions)

# Remove row with TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
].reset_index(drop=True)

print("\nAfter removing TransactionID 109:")
print(transactions)

# Delete Discount column
transactions = transactions.drop(columns=['Discount'])

print("\nFinal DataFrame after deleting Discount column:")
print(transactions)


# ============================================================
# FINAL OUTPUT
# ============================================================

print("\n" + "=" * 60)
print("FINAL TRANSACTIONS DATAFRAME")
print("=" * 60)

print(transactions)

print("\n" + "=" * 60)
print("ASSIGNMENT 1 COMPLETED SUCCESSFULLY!")
print("=" * 60)

PYTHON DA ASSIGNMENT 1: NUMPY AND PANDAS

PART 1: NUMPY ARRAY OPERATIONS

1. Week 1 Temperature Array:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

2. Inspection and Properties:
Shape: (7,)
Data Type: float64
Number of Elements: 7

3. Temperature in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144

4. Array Slicing and Indexing:
First three days: [22.5 25.3 20.8]
Weekend (last two days): [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

5. 2D NUMPY ARRAY

Temperatures for two weeks:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

6. 2D Array Properties:
Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14

Week 1 temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2 temperatures:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

Week 1 weekend:
[24.8 21.9]

Week 2 weekend:
[22.8 20.1]

PART 2: PANDAS SERIES

1. Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4 